package com.usaa.entity;
// Generated 16 Feb, 2018 2:09:18 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Expences generated by hbm2java
 */
@Entity
@Table(name = "expences", catalog = "splitapp")
public class Expences implements java.io.Serializable {

	private int expenceId;
	private long amount;
	private String description;

	public Expences() {
	}

	public Expences(int expenceId, long amount) {
		this.expenceId = expenceId;
		this.amount = amount;
	}

	public Expences(int expenceId, long amount, String description) {
		this.expenceId = expenceId;
		this.amount = amount;
		this.description = description;
	}

	@Id

	@Column(name = "expenceId", unique = true, nullable = false)
	public int getExpenceId() {
		return this.expenceId;
	}

	public void setExpenceId(int expenceId) {
		this.expenceId = expenceId;
	}

	@Column(name = "amount", nullable = false)
	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
