package com.usaa.entity;
// Generated 16 Feb, 2018 2:09:18 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "groups", catalog = "splitapp")
public class Groups implements java.io.Serializable {

	private int groupId;
	private String groupName;

	public Groups() {
	}

	public Groups(int groupId) {
		this.groupId = groupId;
	}

	public Groups(int groupId, String groupName) {
		this.groupId = groupId;
		this.groupName = groupName;
	}

	@Id

	@Column(name = "groupId", unique = true, nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "groupName")
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

}
